package tk.lokiShelter.db.dao;

import java.util.List;
import tk.lokiShelter.db.domain.LsAdminPermissionRelation;
import tk.lokiShelter.db.domain.LsAdminPermissionRelationExample;

public interface LsAdminPermissionRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_permission_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_permission_relation
     *
     * @mbg.generated
     */
    int insert(LsAdminPermissionRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_permission_relation
     *
     * @mbg.generated
     */
    int insertSelective(LsAdminPermissionRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_permission_relation
     *
     * @mbg.generated
     */
    List<LsAdminPermissionRelation> selectByExample(LsAdminPermissionRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_permission_relation
     *
     * @mbg.generated
     */
    LsAdminPermissionRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_permission_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LsAdminPermissionRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_permission_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LsAdminPermissionRelation record);
}