package tk.lokiShelter.db.dao;

import java.util.List;
import tk.lokiShelter.db.domain.LsMenu;
import tk.lokiShelter.db.domain.LsMenuExample;

public interface LsMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_menu
     *
     * @mbg.generated
     */
    int insert(LsMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_menu
     *
     * @mbg.generated
     */
    int insertSelective(LsMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_menu
     *
     * @mbg.generated
     */
    List<LsMenu> selectByExample(LsMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_menu
     *
     * @mbg.generated
     */
    LsMenu selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LsMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LsMenu record);
}