package tk.lokiShelter.db.dao;

import java.util.List;
import tk.lokiShelter.db.domain.LsPermission;
import tk.lokiShelter.db.domain.LsPermissionExample;

public interface LsPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_permission
     *
     * @mbg.generated
     */
    int insert(LsPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_permission
     *
     * @mbg.generated
     */
    int insertSelective(LsPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_permission
     *
     * @mbg.generated
     */
    List<LsPermission> selectByExample(LsPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_permission
     *
     * @mbg.generated
     */
    LsPermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LsPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LsPermission record);
}